version: '3.8'

services:
  djangoGenPasswd:
    restart: always
    image: yourImageName
    #command:
    #- --loglevel warning
    volumes:
    - /data/django/logs:/data/logs:Z
    ports:
    - "80:8080"
    environment:
    - DJANGO_DEBUG=True
    - DJANGO_SECRET_KEY="xxxxxxx"
    - DJANGO_LOG_LEVEL=INFO
    networks:
      - django3


networks:
  django3:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/24
